name: ' alist upload'
author: 'wigeboy'
description: 'Upload file to your alist driver'
inputs:
  filename:
    description:'which file you want to upload,with file path'
    required: true
    default:''
  alist_url:
    description:'your alist full url,http://url.cn:8000'
    required: true
    default:''
  to_path:
    description:'the alist path you want upload to,/guest/upload'
    required: true
    default:''
  username:
    description:'your alist username'
    required: false
    default:''
  password:
    description:'your alist password'
    required: false
    default:''

runs:
  using: "composite"
  steps: 
    - run: $GITHUB_ACTION_PATH/upload.sh ${{ inputs.filename }} ${{ inputs.to_path }} ${{ inputs.alist_url }} ${{ inputs.username}} ${{ inputs.password}}
      shell: upload.sh
branding:
  icon: 'terminal'
  color: 'gray-dark'
